### ISSUE TITLE
Unable to add custom tags in Next.js app on Windows

### ISSUE THREAD

**Issue by SamuelQuinones** [markdoc/markdoc#85]
### What happened?

When running a new NextJS app on a **Windows** machine running **Node v14.19.3** using the markdoc example, the app fails to load, throwing a failed to compile error:

![image](https://user-images.githubusercontent.com/51345689/172937002-1a1ed9d6-ada5-43f2-ac57-ccea86242811.png)

After some tinkering - I found that by removing the tags, the app / page would finally render.

### To reproduce

 - run `npx create-next-app --example https://github.com/markdoc/markdoc-starter`
 - run `npm run dev`
 - App will fail to load and show the error above.

### Version

0.1.2

### Additional context

I tried setting up the project on a **M1 Mac** running **node v16.13.0** and the app was able to compile and render. So I'm wondering if this is related to the OS or possibly the node version.

**Comment by mfix-stripe** [comment]
@SamuelQuinones can you try installing `0.1.4`? Issues with `.tsx` got resolved in that version.

**Comment by SamuelQuinones** [comment]
@mfix-stripe both `@markdoc/markdoc` and `@markdoc/next.js` were set to latest in the package.json, I ran `npm i @markdoc/markdoc@latest` and `npm i @markdoc/next.js@latest` and ended up with this:

```json
"dependencies": {
    "@markdoc/markdoc": "^0.1.2",
    "@markdoc/next.js": "^0.1.4",
    "next": "latest",
    "prismjs": "^1.28.0",
    "react": "latest",
    "react-dom": "latest"
  },
```

Issue still persists

**Comment by SamuelQuinones** [comment]
An update:

I tried creating / running the app on Another windows machine, this one using node v16.13.0.

I get the same error so it looks it might be OS / platform related?

**Comment by mfix-stripe** [comment]
> I get the same error so it looks it might be OS / platform related?

It definitely seems to be that way. Marked the issues as `os:windows`. This actually seems to be unrelated to Markdoc, and is simply an issue with our Next.js app being able to parse the JSX in the `.tsx` file (error points at the first `<` of a JSX element).

**Comment by arranf** [comment]
@mfix-stripe Can we rename this issue to something that identifies this is Windows?

**Comment by arranf** [comment]
@mfix-stripe I'd be happy to fix the issue here but I don't know which ballpark to look!

Any ideas?

**Comment by mfix-stripe** [comment]
@arranf it definitely has something to do which how files are being resolved here: https://github.com/markdoc/next.js/blob/main/src/loader.js

I thought this issue had been fixed with: https://github.com/markdoc/next.js/commit/a5ecea39c2e44d4d44bfbd58fcf125453e4932d9 and https://github.com/markdoc/next.js/commit/d6f933465f4f0d340c38546de53f3b358b379d5e, but I guess some still remain.

**Comment by thecrypticace** [comment]
Hi, I was looking into this to see if I could PR a solution (not there yet).

From my investigation this _could_ be an issue with Markdoc but it also could be an issue with Next.js and how it's webpack rules are set up and work on Windows.

The loader calls `readDir()` which results in output from the loader like this:
```js
// … clipped …
import * as tags from '/Users/myusername/project/markdoc/tags.js'
import * as nodes from '/Users/myusername/project/markdoc/nodes.js'
// … clipped …
```

Using the absolute paths like this breaks. It's like Next.js doesn't see this as a valid js/jsx file and doesn't process run it through any loaders. You can reproduce this outside of markdoc by creating an index.jsx file in Next.js and writing the same imports.

However, if you use relative paths for the imports (in the index.jsx file) then Next.js is happy:

```js
import * as tags from '../../markdoc/tags.js'
import * as nodes from '../../markdoc/nodes.js'
```

Not sure if this is helpful yet but it's some info that could help 🤷

**Comment by arranf** [comment]
This seems like a fix would be to convert it to use non absolute paths on Windows?

**Comment by mfix-stripe** [comment]
Thanks @thecrypticace.

@arranf I am not sure we should should convert to non-absolute paths on Windows yet. 

However, there might be a fix involved with _not_ using `.posix` in a place or two here: https://github.com/markdoc/next.js/blob/main/src/loader.js. 

Using `posix` fixed one issue for me in the past (https://github.com/markdoc/next.js/pull/5/files) , but might have introduced another, and it's difficult for me to verify on Windows since I don't have access to a Windows machine.

**Comment by thecrypticace** [comment]
@mfix-stripe Yep, I think not using POSIX paths would fix it. The Next.js config for js, jsx, ts, tsx, etc… files does not use POSIX paths for the includes array which is the source of the issue:

```js
[
  'C:\\Users\\myusername\\project',
  /next[\\/]dist[\\/]shared[\\/]lib/,
  /next[\\/]dist[\\/]client/,
  /next[\\/]dist[\\/]pages/,
  /[\\/](strip-ansi|ansi-regex)[\\/]/
]
```

**Comment by mfix-stripe** [comment]
> @mfix-stripe Yep, I think not using POSIX paths would fix it. The Next.js config for js, jsx, ts, tsx, etc… files does not use POSIX paths for the includes array which is the source of the issue:
> 
> ```js
> [
>   'C:\\Users\\myusername\\project',
>   /next[\\/]dist[\\/]shared[\\/]lib/,
>   /next[\\/]dist[\\/]client/,
>   /next[\\/]dist[\\/]pages/,
>   /[\\/](strip-ansi|ansi-regex)[\\/]/
> ]
> ```

Agreed. I think we might be able to just remove all the `normalizeAbsolutePath` and just update the tests. The tests need to work on both unix and windows, which is a little tricky, but we just need to hack the paths so they are identical.

**Comment by mfix-stripe** [comment]
@thecrypticace @SamuelQuinones @arranf could one of you try installing [`0.1.5-0`](https://github.com/markdoc/next.js/releases/tag/0.1.5-0) and seeing if that fixes the issue?

**Comment by thecrypticace** [comment]
_almost_ — the slashes need to be double escaped because they're going into a string:

<img width="1104" alt="Screen Shot 2022-06-28 at 14 58 51" src="https://user-images.githubusercontent.com/614993/176261354-6f96864d-85d6-4649-8e54-be47c00faabb.png">

**Comment by mfix-stripe** [comment]
> _almost_ — the slashes need to be double escaped because they're going into a string:
> 
> <img alt="Screen Shot 2022-06-28 at 14 58 51" width="1104" src="https://user-images.githubusercontent.com/614993/176261354-6f96864d-85d6-4649-8e54-be47c00faabb.png">

@thecrypticace I think the error above actually has to do with the imports starting w/ `C:`, and webpack not understanding is correctly. I _believe_ the escaping issue is just broken on the error overlay, not with the actual imports themselves.

**Comment by mfix-stripe** [comment]
@thecrypticace do you think enabling [`preferAbsolute`](https://github.com/webpack/enhanced-resolve#resolver-options) could resolve this?

**Comment by thecrypticace** [comment]
I don't think preferAbsolute would end up changing the result.

**Comment by mfix-stripe** [comment]
Thanks @thecrypticace! If you edit your node_modules locally with [these changes](https://github.com/markdoc/next.js/pull/11/files), does that fix your issue?

**Comment by thecrypticace** [comment]
@mfix-stripe It does! 💯

**Comment by mfix-stripe** [comment]
> @mfix-stripe It does! 💯

Rad! Just released https://github.com/markdoc/next.js/releases/tag/0.1.5-1. @thecrypticace could you install this latest version and double-check that it works for you? _Really_ appreciate your help on this 🙂

**Comment by thecrypticace** [comment]
@mfix-stripe yep that does indeed work 🎉

**Comment by mfix-stripe** [comment]
🙌 fantastic! Thanks for all your help here @thecrypticace 🙏

**Comment by mfix-stripe** [comment]
https://github.com/markdoc/next.js/releases/tag/0.1.5
